[package]
name = "overrider"
version = "0.3.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "1.0.17"
syn = {version = "1.0.23", features = ["full", "extra-traits"]}
quote = "1.0.6"

[lib]
proc-macro = true