[workspace]

members = [
    "overrider",
    "overrider_build",
    "examples/hello_world",
    "examples/methods",
    "examples/priorities",
    "examples/finals",
    "examples/flags",
    "examples/library",
]