[package]
name = "flags"
version = "0.1.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
overrider = "^0.5.0"
clap = "2.33.1"
lazy_static = "1.4.0"

[build-dependencies]
overrider_build = "^0.5.0"